### ISSUE TITLE
Admin GUI Part 2

### ISSUE THREAD

**Issue by Gonzalo8642** [caribou-crew/mezzo#19]
Routes do not show or inform user of active variant selected for a route.

When using new tab to show response. we should have route/variantName as the title on the tab.

Alignment issues with each route tile.

nav header for resetting should actually reset.

fuzzy matching on search bar

**Comment by NSwanson1** [comment]
Aside from the nav header i think the rest of these items are at the most basic level addressed. We can move the nav header into its own issue.

**Comment by NSwanson1** [comment]
addressed in https://github.com/caribou-crew/mezzo/pull/20
